### ISSUE TITLE
Potential issue with TableDesc w.r.t table existence

### ISSUE THREAD

**Issue by jcoveney** [Cascading/cascading-jdbc#12]
https://github.com/Cascading/cascading-jdbc/blob/2.5/cascading-jdbc-core/src/main/java/cascading/jdbc/TableDesc.java#L171-L182

It seems weird to me that getTableExistsQuery() checks canQueryExistence(). It seems like we are conflating two ideas. If canQueryExistence() is false, it should mean that there is no way to query existence in this database, right? But in getTableExistsQuery(), it uses this to mean "fall back to the default for the database," which is odd. This means that a user who first checks canQueryExistence() could get false becaue the tableDesc is not set, but getTableExistsQuery() could still return a valid query.

Seems like a bug to me. Thoughts?

**Comment by joeposner** [comment]
While slightly odd, this is necessary since data sources are inconsistent about how they support table discovery and what the optimal way to discover this is.
There are some JDBC-like data sources that don't support table discovery via a SQL queries, which is why the canQueryExistence() method exists. And there are some databases that have specific queries that are more precise and useful than doing a "select from table where 1 = 0"
The overall logic is correct:
if ( the data source supports SQL queries of table discovery )
then 
   if (we know the syntax for the good query) 
      use it;  
   else 
      do a  "select from table where 1 = 0"
else
  assume the provider has someway to determine the existence of the table

**Comment by jcoveney** [comment]
Hmm. I guess the part that is vague is that if I am using this, if getTableExistsQuery() returns something, then I can indeed query for existence, no? so canQueryExistence() returning false would be misleading. What canQueryExistence() is really doing, it seems, is telling us if we can query for existence _intelligently_, not if we can do it at all. Right?

**Comment by joeposner** [comment]
Yes, that's exactly right. The canQueryExistence() tells you if there's a clean way to do it via a SQL query. The getTableExistsQuery() query tells you the SQL to use.
It would probably be cleaner if canQueryExistence() was named canTestExistenceWithSQL() and getTableExistsQuery() was renamed getTableExistsSQLQuery()
